### ISSUE TITLE
Trying to load a Ring Door bell stream - rtsp

### ISSUE THREAD

**Issue by matheuscanela** [i8beef/node-red-contrib-castv2#103]
Hey folks!
I'm trying to automate using the CAST from node-red; however, when I attempt to add the cast, it doesn't work.

**The stream works fine using the following formats:**
1. Through the VLC app
2. If I go to the Google Cast plugin in the Home Assistant dashboard and ask it to play from the cameras - which I added as per the manual
3. Using the Home Assistant "call service" to play the camera via stream

I tried the cast and castv2 nodes from the palette, but I'm still getting the errors below:

**From Cast:**
The device tries to open the video, but nothing happens, and node-red returns "Not able to load media:Load failed Not able to load the media."

**From Cast v2:**
Similar to the above, but it returns the error "Error: Unknown command."

Also, the HA logs shows the errors below
- Failed to cast media http://192.168.4.10:8123/api/hls/*****05a43859c6eda18d539a95/master_playlist.m3u8?authSig=**** from internal_url (http://192.168.4.10:8123). Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
- Failed to cast media rtsp://ring:ring@192.168.4.10:8554/****576fa69a_live. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
- Failed to cast media rtsp://192.168.4.10:8554/****576fa69a_live. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
- Failed to cast media rtsp://homeassistant:8554/*****576fa69a_live. Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
- Failed to cast media http://192.168.4.10:8123/api/hls/*****cfc7e5550bdd2d64db450f2f820df2c4bcdca6d730d63f0f30/master_playlist.m3u8?authSig=***** from internal_url (http://192.168.4.10:8123). Please make sure the URL is: Reachable from the cast device and either a publicly resolvable hostname or an IP address
Error from stream worker: Error opening stream (INVALIDDATA, Invalid data found when processing input) rtsp://****:****@192.168.4.10:8554/****6fa69a_live
Error from stream worker: Timestamp discontinuity detected: last dts = 63243720, dts = 922937504

If I open the IP in VLC, it works normally. Also, all the devices are on the same network without any segregation. I have also tried using it without a password and with the hostname instead of the IP, but the issue persists.

The reason why I want to use the cast is that I want to set the live option and avoid the buffer settings.

Configuration

**cast**
![Screenshot 2024-05-05 015446](https://github.com/tsightler/ring-mqtt/assets/6635137/f159e2a9-23b3-436d-9867-d43ee9e29044)

**castv2**
![castv2](https://github.com/tsightler/ring-mqtt/assets/6635137/822e5983-eca6-4c9c-998a-19e608005606)
^^ the above image shows @192... but I removed the @ and it didn't work too.

rtsp is coming from this addon
https://github.com/tsightler/ring-mqtt

**Comment by i8beef** [comment]
In your image you are attempting to cast an RTSP stream. You can't do that. The Cast protocol only supports HLS, DASH, and WebRTC for streaming.

I am not sure what your other logs are telling you, but you can see it attempting to convert the RTSP stream to HLS in there. I use Frigate to convert my camera RTSP streams to HLS for streaming to cast targets when I want to. It reads the RTSP stream and provides and HLS stream URL (m3u8) which is the URL I send to my Cast targets.

This node does not do any sort of RTSP conversion for you.

**Comment by matheuscanela** [comment]
Thanks @i8beef for replying back to me, you actually helped me to find the issue.

I solved the problem by adding the go2rtc add-on and streaming it using [DashCast](https://flows.nodered.org/node/node-red-contrib-castv2), which is quite quick. Not sure if it is the best solution, but works as expected! Also, while researching, I found a ticket on the internet complaining that the Ring doorbeels (which is my case) was starting every 10 minutes without stopping. I noticed the same issue, but I fixed it by asking the CASTv2 to stop casting before reaching 10 minutes - as the camera closes the stream after 10 min. Otherwise, I think the Google Nest continues to open the stream, even if it times out.

However, I still don't understand how the native Google Cast integration works just by clicking in the camera integration. 

If any other suggestion, please let me know.

**Comment by i8beef** [comment]
go2rtc is actually what Frigate uses for restreaming WebRTC under the hood. That page you are DashCasting has a JS based player on it that just plays the WebRTC stream full screen, and then casting it directly like that is essentially a "poor man's custom cast receiver". Im sure it has caveats, but honestly that's a fairly clever way to do it. I scrape that go2rtc JS out and use it to embed WebRTC camera streams on my node-red dashboards because they have a lower latency than HLS.

I was actually wrong, the cast protocol does NOT seem to support WebRTC natively: the Google Home camera intents do, which is what I was trying to work with before on another project, and its a pain in the butt. 

The CAST protocol supports HLS (and DASH, but thats just Google branded HLS), and it doesn't even support LL-HLS (low latency) if I remember right. https://developers.google.com/cast/docs/media

I restream RTSP to HLS via a docker image called `rtsp-simple-server`, and then just do a simple media cast of that m3u8 URL to the cast devices. HLS by definition is several seconds behind, though, which is why WebRTC is better if you can figure out a way to do it. (LL-HLS is actually pretty close, but as I said I don't think that's supported by Google Cast).

**Comment by i8beef** [comment]
Closing as you have a work around, which seems as close as you'll get with the native cast protocol.
