### ISSUE TITLE
Netflix status is not shown

### ISSUE THREAD

**Issue by JGoor** [i8beef/node-red-contrib-castv2#52]
This is about a 'Cinema-mode' flow that dims lights when playing content and lights up the lights when paused.

When watching Youtube, ths following statuses are sent: 'PLAYING' and 'PAUSED', depending on the status.
However when I watch Netflix, the node does not show anything.

This is the reproduction flow (change Chromecast IP address):
`[{"id":"255e1234.c4c896","type":"debug","z":"f6f2187d.f17ca8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":870,"y":420,"wires":[]}]`

Is there a solution for this?

**Comment by i8beef** [comment]
I can try a Netflix cast tonight and see what I get. Its up to the individual cast receiver app authors to "do the right thing" here... most do because the generic cast controls on phones / browsers are dependent on these commands / status updates to work right too. 

Just a thought, you are CASTING netflix and not running it on an Android TV device correct? The latter has nothing to do with the cast protocol, and won't interact with it at all.

**Comment by JGoor** [comment]
I am using ChromecastV2 if that's what you mean.
Nothing exotic here.
Mind that casting Youtube _is_ working as expected; the provided example flow does its job. Only Netflix (and ' Videoland', as I understand) do not provide the proper triggers.

**Comment by i8beef** [comment]
It actually looks like the appId for Netflix wasn't correct anymore when I started a session locally. I changed it to be correct, and hopefully this will work for you. Try 3.2.12.

**Comment by i8beef** [comment]
Correction, try 3.2.13. There was some additional missing Netflix code.... working locally now.

**Comment by JGoor** [comment]
That did the trick!
Youtube now gives 'PAUSED' and Netflix 'BUFFERING' when paused.
Thanks for you quick reply @i8beef !

**Comment by ThinkPadNL** [comment]
The Dutch 'Videoland' app doesn't show any output in Node-RED. Can you add support for this one?
I see in the code that you need a certain ID to detect what is playing. Let me know how i can retrieve this information for you.
