### ISSUE TITLE
Videoland (Dutch streaming app) info not shown

### ISSUE THREAD

**Issue by ThinkPadNL** [i8beef/node-red-contrib-castv2#53]
The Dutch 'Videoland' app doesn't show any output in Node-RED. Can you add support for this one?
I see in the code that you need a certain ID to detect what is playing. Let me know how i can retrieve this information for you.

**Comment by ThinkPadNL** [comment]
It looks like the App ID is `A134ADAD`.

**Comment by i8beef** [comment]
I will one up you.

I just release 4.0.0, which SHOULD support generic media commands on ANY receiver that claims to support the generic media control namespace of the cast protocol... I've been looking for a way to do that for a while, and this seems like a good time to try something out since I'll be around to support for the holiday season.

I might change the underlying implementation around a few more times before its where I like it, but it seems functional in all my tests so far, so I think I have a baseline for supporting this now.

**Comment by ThinkPadNL** [comment]
You are my hero for today. It worked instantly after updating the node in Node-RED 👍 I now get the 'playing' and 'paused', but can also play/pause the current playing media from within Node-RED.

Thanks a lot!
