### ISSUE TITLE
Power command

### ISSUE THREAD

**Issue by TimoTielens** [i8beef/node-red-contrib-castv2#54]
Hi,

First of all I'm loving this repo. Keep up the good work 👍. 

I can ask my google home to turn off/on my tv by saying "Hey Google, Turnoff TV". I would like to have this option in NodeRed as well.  I did not find an option for this in your repo. Could this be added?

Timo

**Comment by i8beef** [comment]
The only way this is related to the Cast protocol is if you are using CEC, and the TV automatically turns on when you cast to the cast device connected to the TV. Outside that, you are looking at a Google Home integration instead to control the actual TV power state via (a) a connected TV protocol, or (b) Harmony Hub or other IR blaster controllers. 

If you have CEC enabled on the TV and working for this, ANY media cast to the cast device should turn it on.

Otherwise you'd have to have some other option for actually triggering your TV power events that you can trigger through node-red (for a networked TV, there might be a node for talking to it).

Sorry man, unfortunately dedicated CEC commands aren't exposed by the cast protocol.
