### ISSUE TITLE
Can't have individual IP addresses for two different cast targets

### ISSUE THREAD

**Issue by oh2xx** [i8beef/node-red-contrib-castv2#69]
I have a Nest Audio upstairs and a Google home mini downstairs. I have successfully used the one upstairs but I am not able to add the home mini as both of the castv2 nodes seem to take just one common  IP address instead of two different individual addresses. If I change one of the IP addresses the end result is that the two will always have the some one. 

BR,

Kari

**Comment by oh2xx** [comment]
Well there seems to be a drop down menu "Add new castv2 connection..." . That solved the issue.

**Comment by i8beef** [comment]
I can think of no way that could be possible. IP addresses don't really work that way... I suspect however you are getting the IP address (Google Home app?) must be buggy here and is reporting incorrectly.

**Comment by oh2xx** [comment]
I was changing the destination IP address in the Node-Red in castv2 properties, not in Google home app. Both cast devices have fixed IPs. And I know IP addressing since 1986 :-)
Anyway all ok now and both cast targets work as expected.

**Comment by i8beef** [comment]
Ah, then it sounds like you were sharing a connection between the nodes instead of creating one per node. When you click in the dropdown for the connection, there's an "add new castv2-connection" option. You have to create connections and then select them in the node itself.

It sounds like you created ONE connection, and reused it between two nodes instead.

**Comment by oh2xx** [comment]
Yes
