### ISSUE TITLE
Starting radio e.g. Bayern 3

### ISSUE THREAD

**Issue by krilor1** [i8beef/node-red-contrib-castv2#81]
Is it possible to start radio e.g. Bayern 3 with tunein and if yes, how would the flow looks like?

**Comment by i8beef** [comment]
No, that's not really how the Google Cast protocol works. The only "generic" control that it exposes are the media control commands that lets Google implement media controls in say the Android notification shade, etc., but NOT the a "load media" command as that would be so specific to a given application. They expose a generic "DefaultMediaReceiver" cast app that lets you send individual supported media files to play on the cast device, which this node supports. Once an app is launched and has loaded media, this node can also CONTROL that media playback as long as they followed Google's standards (basically just like you get the play, pause, stop, next, prev media control interface in your android phone's notification shade once something starts casting in your network).

This means there is no way to support a given app without basically BEING that app. The only one that I make any attempt to support today is YouTube due to popular demand and availability of documentation to implement (Most apps cant be supported on principle just because the details, keys, auth mechanisms, etc. are not in any way documented or supplied).

Unfortunately, that means your request is out of scope. You CAN LAUNCH any given app, if you can find the right app id for it (again: undocumented), but without the app specific load semantic support, that usually isn't very helpful.

**Comment by i8beef** [comment]
Closing as out of scope
