### ISSUE TITLE
Microsofts Edge_say instead of Google_translate_say

### ISSUE THREAD

**Issue by yfands** [i8beef/node-red-contrib-castv2#89]
Goodday,

I really like the Castv2 node (installed in Home assistant), but the 'default' google_translate_say voice in dutch is al little dull. So I installed Microsoft Edge TTS and named it Edge_say. The Microsoft Edge TTS has more voices, I like them better. I want Castv2 to be able to use Microsoft Edge TTS. I tried to implement in the payload 'tts_service' or just 'service', I dont get an error but no MS Edge either. Is it possible to change the tts_service? Or something that can be implemented? Regards Frank

**Comment by i8beef** [comment]
The built in TTS support is a hold over anyway. Google continuously attempts to kill the free service that underlies it, to the point where its no longer the suggested method of doing TTS. In essence, it is just a MEDIA cast of of a hard coded URL that takes arguments and provides an MP3.

Because Google has been less than helpful here, the recommendation is to create your own implementation, or use another service, and just use a simple MEDIA cast.

See: https://github.com/i8beef/node-red-contrib-castv2/wiki/TTS-Alternatives

If you find a way to make that work for you, let me know, and I can add it to the Wiki though.

**Comment by i8beef** [comment]
Closed as out of scope.
