### ISSUE TITLE
Casted Youtube video shows ads (youtube premium) 

### ISSUE THREAD

**Issue by ignacioletelier** [i8beef/node-red-contrib-castv2#96]
node-red@v3.1.0
node-red-contrib-castv2@v4.3.0

Hello, first of all, I want to thank you for the code, it has been very useful to me.

I have just one problem:

I regularly use the node to cast YouTube videos to a TV, which shows Ads before playing the video.

I understand that even though the TV is logged in with YouTube Premium, the device from which the cast is initiated (node-red) does not have a logged-in session. Is there any way to cast with a logged-in session, or is there a way to resolve the issue with the Ads?

Thank you in advance.

**Comment by i8beef** [comment]
Under the hood, anything outside the DefaultMediaReceiver isn't really "cast" functionality... YouTube falls under that, so when you use it its basically LAUNCHING the YouTube app and then interacting with YouTube APIs to load your requested video into your play queue on the YouTube servers (ie, the cast device is just a dumb monitor in these cases, and the APP has all the functionality here). Its not really viable to support the individual APIs of all the possible apps you can launch on a cast device since all those APIs are special snowflakes, though I DO support some specific ones (YouTube being the main one)...

Meaning, no, controlling the app beyond basic "load" functionality is outside the scope of this node right now. I actually would have suspected that given that it launches YOUR app which is already logged in, that it would just inherit that state. 🤷 

As it stands though if it doesnt do that, no I don't think I would looking to hold credentials / handle token management, etc. for a single app.

**Comment by ignacioletelier** [comment]
I completely understand. Thank you very much for taking the time to share the details with us.
